volumes:
  database-v:
    name: "database-v"
services:
  database:
    image: a30drian/database:1.0.0 
    container_name: postgres-db
    environment:
      POSTGRES_DB: m-busi
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
     - database-v:/var/lib/postgresql/datatest123412
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d m-busi"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: a30drian/backend:latest
    ports:
      - "8080:8080"
    environment:
      DB_ADDR: "postgresql://user:password@database:5432/m-busi?sslmode=disable"
    depends_on:
      database:
        condition: service_healthy
    restart: on-failure