services:

  backend:

    build:
      context: . # The build context is the current directory (where docker-compose.yml is).
      dockerfile: ./Dockerfile # Path to your Dockerfile relative to the context.

    ports:
      - "8080:8080"

    environment:
      DB_ADDR: postgres://user:password@db:5432/m-busi?sslmode=disable
      DB_MAX_OPEN_CONNS: 30
      DB_MAX_IDLE_CONNS: 30
      DB_MAX_IDLE_TIME: 15m

    depends_on:
      - db
    restart: on-failure

  # Service for the PostgreSQL database.
  db:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_DB: m-busi
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
     - db_data:/var/lib/postgresql/data
      - ./createdatabase.sql:/docker-entrypoint-initdb.d/databaseSchema.sql
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d m-busi"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  db_data: