name: CI/CD Pipeline for Backend

on:
  push:
    branches:
      - SC-50-Izdelava-posredniške-storitve 
    paths:
      - 'backend/**' 

jobs:
  build_and_push_backend_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend # Pomembno: kontekst je mapa 'backend'
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:latest # Vaše uporabniško ime in ime slike
name: CI/CD Pipeline for Backend

on:
  push:
    branches:
      - SC-50-Izdelava-posredniške-storitve 
    paths:
      - 'backend/**' 

jobs:
  build_and_push_backend_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend 
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:latest 