name: CI/CD Pipeline for Backend

on:
  push:
    branches:
      - SC-50-Izdelava-posredniške-storitve
    paths:
      - "spletnoProgramiranje/backend/**"

jobs:
  build_and_push_backend_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./spletnoProgramiranje/backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:latest

  notify_server:
    needs: build_and_push_backend_image
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook to server
        run: |
          curl -X POST ${{ secrets.WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Event: deployment" \
            -H "X-Hub-Signature: ${{ secrets.WEBHOOK_SECRET }}" \
            -d '{
              "event": "new_backend_image",
              "repository": "${{ github.repository }}",
              "tag": "latest",
              "commit_sha": "${{ github.sha }}"
            }'
