name: Trigger on new branch from develop

on:
  create:
    branches:
      - '**'   # This matches all branch creations

jobs:
  run-on-branch-create:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Branch '${{ github.ref }}' was created from '${{ github.base_ref || 'unknown' }}'"
